title: YouTube-DorGen
logo: ./icons/youtube-logo.svg
supportedLanguages: []
style: red
properties: []
description: Wiki документация YouTube-DorGen
versions: []
relatedLinks:
  - url: https://t.me/meteorburn
    title: Telegram
    icon: lucide-send
  - url: https://www.youtube.com/@dorgen-software
    title: YouTube
    icon: youtube-icon
