title: YT Dorgen Docs
logo: ./icons/youtube-tutorials.svg
supportedLanguages: []
style: red
properties: []
description: Wiki Документация
versions: []
relatedLinks:
  - url: https://t.me/meteorburn
    title: Telegram
    icon: lucide-send
  - url: https://www.youtube.com/@dorgen-software
    title: YouTube
    icon: youtube-icon
